apiVersion: v1
kind: Service
metadata:
  name: guestbook-app-service
 
spec:
  selector:     
    app: guestbook-app
    name: guestbook-app-pod
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008 
